export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  DATA_LOGIN : 'DATA_LOGIN',
  SIGNOUT : 'SIGNOUT',
  SIGNUP : 'SIGNUP',
  CATEGORY : 'CATEGORY',
  ADD_CATEGORY : 'ADD_CATEGORY',
};
